"""add_question_reports

Revision ID: 073ada4209be
Revises: ce9032ddd241
Create Date: 2026-05-04 10:26:10.428696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073ada4209be'
down_revision: Union[str, Sequence[str], None] = 'ce9032ddd241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('replaced_by', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('report_count', sa.Integer(), nullable=True))
    op.create_index('idx_q_active', 'questions', ['is_active'], unique=False)
    op.create_foreign_key(None, 'questions', 'questions', ['replaced_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_index('idx_q_active', table_name='questions')
    op.drop_column('questions', 'report_count')
    op.drop_column('questions', 'replaced_by')
    op.drop_column('questions', 'is_active')
    # ### end Alembic commands ###
